# Generated by Django 5.1.4 on 2026-07-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('predicted_aqi_us', models.FloatField(blank=True, help_text='Forecast next US AQI', null=True)),
                ('predicted_category', models.CharField(blank=True, help_text='Predicted pollution band', max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('input_features', models.JSONField(blank=True, default=dict, help_text='Input snapshot used for the prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='data_api.airqualityreading')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', '-created_at'], name='predictor_p_city_c2bc29_idx')],
            },
        ),
    ]
