# Generated by Django 5.1.4 on 2026-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('aqi_us', models.IntegerField(blank=True, help_text='US AQI', null=True)),
                ('aqi_cn', models.IntegerField(blank=True, help_text='China AQI', null=True)),
                ('main_pollutant_us', models.CharField(blank=True, max_length=10)),
                ('main_pollutant_cn', models.CharField(blank=True, max_length=10)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='Relative humidity %', null=True)),
                ('pressure_hpa', models.IntegerField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Degrees', null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=10)),
                ('source_ts', models.DateTimeField(help_text='Reading time reported by IQAir (UTC)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When our system fetched it')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['city', 'source_ts'], name='data_api_ai_city_10a31c_idx'), models.Index(fields=['-fetched_at'], name='data_api_ai_fetched_703194_idx')],
            },
        ),
    ]
